import { FC } from 'react'
import axios from 'axios'
import data from "@/data/pokemmo.mock.data.json"
import { Dex } from '@pkmn/dex';
import { Generations } from '@pkmn/data';
import PokemonCard from '@/components/PokemonCard';

interface MovepoolItem {
    [move: string]: string[];
}

interface pageProps {

}

export interface Pokemon {
    number: string;
    name: string;
    types: string[];
    abilities: string[];
    tier: string;
}

const page: FC<pageProps> = async ({ }) => {
    const gens = new Generations(Dex);
    // const movepool = await gens.get(5).learnsets.learnable(pokemon);

    // Generated by https://quicktype.io
    const pokemons: Pokemon[] = data.Pokedex.map((data) => data.pokemon);



    return (
        <div className="container py-24" style={{"paddingRight": '2rem'}}>
            <div className="grid grid-cols-3 gap-4 ">
                {pokemons.slice(0, 6).map((pokemon, index) => (
                    <PokemonCard name={pokemon.name} key={index} number={pokemon.number} abilities={pokemon.abilities} types={pokemon.types} tier={pokemon.tier} />
                ))}
            </div>

        </div>)
}

export default page